export const LOAD_RECIPES = '#1 LOAD RECIPES';
export type LOAD_RECIPES = typeof LOAD_RECIPES;

export const LOAD_RECIPE_DETAIL = '#2 LOAD RECIPE DETAIL';
export type LOAD_RECIPE_DETAIL = typeof LOAD_RECIPE_DETAIL;